// <auto-generated />
using System;
using APICore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APICore.Migrations
{
    [DbContext(typeof(NewWEBContext))]
    [Migration("20180718113021_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("APICore.Models.User_Login", b =>
                {
                    b.Property<int>("User_Login_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("User_Login_CreatDT")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("User_Login_EmailAddress")
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("User_Login_Guid")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("User_Login_Name")
                        .HasMaxLength(20);

                    b.Property<string>("User_Login_PassWord")
                        .HasMaxLength(20);

                    b.Property<int>("User_Login_Right");

                    b.Property<string>("User_Login_Sex")
                        .HasMaxLength(5);

                    b.Property<bool>("User_Login_State");

                    b.HasKey("User_Login_ID");

                    b.ToTable("User_Login");

                    b.HasData(
                        new { User_Login_ID = 1, User_Login_CreatDT = new DateTime(2018, 7, 18, 19, 30, 21, 328, DateTimeKind.Local), User_Login_EmailAddress = "2351592225@qq.com", User_Login_Guid = new Guid("4519068c-797c-49bc-9e6c-afead51e108d"), User_Login_Name = "Administrator", User_Login_PassWord = "Administrator", User_Login_Right = 0, User_Login_Sex = "男", User_Login_State = false }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
